apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimallm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimallm-backend
  template:
    metadata:
      labels:
        app: minimallm-backend
    spec:
      containers:
        - name: minimallm-backend
          image: minimallm-backend:latest # <-- Corrected image name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minimallm-secrets
                  key: OPENAI_API_KEY
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minimallm-secrets
                  key: GOOGLE_API_KEY
            - name: DEFAULT_LLM
              value: "openai"
---
apiVersion: v1
kind: Service
metadata:
  name: minimallm-backend
spec:
  selector:
    app: minimallm-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000